### ISSUE TITLE
commit com dois tipos ou mais

### ISSUE THREAD

**Issue by Alcidesfrancisco** [iuricode/padroes-de-commits#20]
gostaria de ver como ficaria um commit que tenha dois ou mais tipos, Fix e Feat por exemplo, pelo menos comigo é bem comum, e acredito que vai agregar valor para seu trabalho e toda a comunidade que consultar esse belo material.

**Comment by rodrigopmatias** [comment]
o ideal seria fazer dois commits, cada commit com sua unidade

**Comment by Alcidesfrancisco** [comment]
Entendi, faz muito sentido... irei melhorar nesse aspecto

**Comment by Graciliana** [comment]
Não seria possivel colocar por exemplo : feat : fix :
