### ISSUE TITLE
[SUGESTÃO] [GIT HOOKS] Fluxo utilizando commit pre-receive / prepare-commit-msg

### ISSUE THREAD

**Issue by tiagolofi** [iuricode/padroes-de-commits#36]
Fala! Tudo beleza? 

Considerando esta documentação sobre [Git Hooks](https://git-scm.com/book/pt-br/v2/Customizing-Git-Git-Hooks). Como seria um script pre-receive capaz de executar um fluxo em que o usuário: complemente com a informação do tipo de alteração e com a mensagem, de forma mais simples. Por exemplo, mostrando as opções possíveis de tipos e emojis disponíveis. Fique a vontade pra encerrar a issue caso não se enquadre no escopo do seu projeto.

**Comment by iuricode** [comment]
Muito obrigado pela contribuição, a comunidade e eu agradecemos por ela.

Já começamos a trabalhar nesta questão para facilitar adicionar o tipo do commit no terminal do usuário.

**Comment by tiagolofi** [comment]
preparei um prompt para integrar o conteúdo do repo com o chatgpt, avaliando o `git diff`, após os testes com sucesso compartilharei aqui na comunidade

**Comment by iuricode** [comment]
Perfeito! Fico no guardo e ansioso por essa grande contribuição.
