### ISSUE TITLE
Qual seria o padrão para uma ação de adição

### ISSUE THREAD

**Issue by peidrao** [iuricode/padroes-de-commits#6]
Olá Iuri, desde já agradeço por disponibilizar esse material tão rico e importante para nós desenvolvedores. 
Estou tentando seguir esse padrão, mas estou com algumas dificuldades para escolher a melhor expressão para determinada situação. Quando adiciono um novo arquivo de configuração é compreendido usar o chore, mas e quando preciso adicionar um arquivo de código, qual seria o melhor?

**Comment by Cadavanaugh** [comment]
Oi Pedro! Quando eu adiciono um novo arquivo de código eu uso o `:sparkles: feat`.
